links:
  facebook: https://www.facebook.com/dennisrstine
  twitter: https://www.twitter.com/dennisstine
  linkedin: https://www.linkedin.com/in/dennisrstine
  github: https://github.com/dennisstine
  hackerrank: https://www.hackerrank.com/dennisstine
aws:
  function:
    name: go-email-sender